# 应用名称
spring:
  application:
    name: study_mybatis
  datasource:
    # 数据库驱动：
    driver-class-name: com.mysql.cj.jdbc.Driver
    # 数据源名称
    name: defaultDataSource
    # 数据库连接地址
    url: jdbc:mysql://localhost:3306/test?serverTimezone=UTC
    # 数据库用户名&密码：
    username: root
    password: root

  # 配置JPA自动生成表
  jpa:
    hibernate:
      # 请勿改动
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
# 应用服务 WEB 访问端口
server:
    port: 8080

#下面这些内容是为了让MyBatis映射
mybatis:
  #指定Mybatis的Mapper文件
  mapper-locations: classpath:mappers/*xml
  #指定Mybatis的实体目录
  type-aliases-package: com.example.study_mybatis.entity


